name: Continuous Integration

on:
  # NOTE: Automatic triggers disabled as the El País Lotto API is no longer available:
  # - push
  # - pull_request
  workflow_dispatch:

jobs:
  continuous-integration:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - uses: actions/checkout@v1
      - name: Test
        run: swift test
